version: '3'

services:
  app:
    container_name: app_multiple
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '8081:80'
    expose:
      - '8081'
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    container_name: mysql_multiple
    image: mysql:8
    environment:
      MYSQL_DATABASE: phalcon_app_multiple
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '3306:3306'